# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4a9eaea726a5d720a25ebaec2b7ea45c7d6ea03013999c5d0063ffc3acd274118ea2a23c0a0d69987aea67516439075c04dfafca41fbc466227a4a94670b577

test:
  secret_key_base: a7396dcfe6582aac2f84a9f4bc3a0ea0c4575d8f2f92aa5d75f505ea710f75365a3da0bfb69a1691aaa9f4ad83d70bc19b93716e3c80bd9ca33f6d6e6c39a2c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
